### ISSUE TITLE
Handling entities missing/obstructed for part of the scenario?

### ISSUE THREAD

**Issue by BenoitHanotte** [driskai/scenario_gym#37]
Hello,

I was trying to generate a scenario from the tracks of vehicles we detect in a video. Some vehicles are not visible at the beginning of the video, thus we do not have their pose at the beginning of the scenario.

For each entity, I generate the `(t, x, y)` trajectory coordinates, but all entities might not be visible for all values of `t` due to obstructions.
When creating the `Scenario` from the list of entities, `BatchReplayEntity` interpolates the trajectories. As far as I understand, it makes the assumption that entities should be present for all timesteps, which leads to incorrect trajectories at the beginning of the scenario for these "partially missing" vehicles.

~~I also could not find any information of supporting "partially missing" entities in the OpenScenario v1.2.0~~
Edit: after looking more into the OpenScenario trajectory schema, it seems `Vertex` has a `time` parameter, so trajectories should be able to only span a subset of the scenario. The issue would seem to be that `State` and `BatchReplayEntity` assume all entities will always be visible in the scenario.

Do you have any recommendation on how I could manage this in scenario-gym?

Thank you!

**Comment by BenoitHanotte** [comment]
I have made some progress on this today by overriding some methods from `State`:

```python
class CustomState(State):

    @classmethod
    def from_state(cls, state: State):
        return cls(
            scenario=state._scenario,
            conditions=None,
            state_callbacks=state.state_callbacks,
        )

    def _reset_data(self) -> None:
        super()._reset_data()
        # Note: Do not initialize the poses yet as we don't know which entity will be visible
        self.poses = OrderedDict()
        self.prev_poses = OrderedDict()

    def update_poses(self, t: float, new_poses: Dict[Entity, np.ndarray]):
        """Update poses of all entities."""
        self.t = t
        self.prev_poses.update(self.poses)

        # Note: we only keep poses for entities visible at time `t`. Other entities will be removed
        # from the `poses` dict.

        for entity, pose in new_poses.items():
            # FIXME: can we rely on the name 'ego' here?
            if entity.ref.lower() == 'ego' or entity.trajectory.t[0] <= t + 1e-5:
                # entity is visible at time `t`, we update its pose
                self.poses[entity] = pose

        for entity in list(self.poses.keys()):
            # FIXME: can we rely on the name 'ego' here?
            if entity.ref.lower() != 'ego' and entity.trajectory.t[-1] < t - 1e-5:
                # entity is not visible anymore at time `t`, we remove its pose
                del self.poses[entity]

        if self.prev_t is not None:
            self.update_statistics()
        for entity, pose in self.poses.items():
            self._recorded_poses[entity].append((self.t, pose))

    def update_statistics(self) -> None:
        """Update entity velocities and distance travelled."""
        # Note: we only consider entities with a pose for the current step.
        # Other entities wil have an unknown velocity.
        self.velocities = OrderedDict.fromkeys(self.scenario.entities)

        for entity in self.poses.keys():
            if self.prev_poses.get(entity) is not None:
                self.velocities[entity] = (
                    self.poses[entity] - self.prev_poses[entity]
                ) / self.dt
                self.distances[entity] += np.linalg.norm(
                    (self.poses[entity] - self.prev_poses[entity])[:3]
                )
```

This fixes the issue with the viewer as you can see on the before and after videos below:
1. before the patch:
![Screen Recording 2023-01-26 at 16 04 12](https://user-images.githubusercontent.com/6229788/214886563-f20ec3e1-151d-41c0-9152-9387a328c24b.gif)

2. after the patch (note the vehicles disappearing as they enter or leave the field of vision):
![Screen Recording 2023-01-26 at 16 01 08](https://user-images.githubusercontent.com/6229788/214886579-4b0a6733-bead-49ce-adb3-cd858c9e5b1d.gif)

**Comment by hamishs** [comment]
Hi @BenoitHanotte, I've started a branch to support this feature [here](https://github.com/driskai/scenario_gym/tree/v0.4) which will be included in the next release (v0.4). Now the simulation should only display entities for duration of their trajectory (you can use the `persist` flag of `ScenarioGym` to recover the old behaviour). Feel free to try this with your scenario and check if the behaviour is as expected. I will keep testing and updating it over the next few days.

One other thing to note is this branch solidifies the definition of the ego in the scenario with a property [`Scenario.ego`](https://github.com/driskai/scenario_gym/blob/v0.4/scenario_gym/scenario/scenario.py#L59).

If you find any bugs or have any feedback let me know!

**Comment by BenoitHanotte** [comment]
Hi @nilsgoldbeck and @hamishs , thanks for looking into it and sorry for the late reply, I have been busy with other topics last week.
Thanks for pointing me to this branch, I'll give it a try later this week once I have a bit more time :)

**Comment by hamishs** [comment]
Hi @BenoitHanotte just to let you know that the latest release of `scenario_gym` (v0.4) adds support for this functionality. By default now entities should only appear for the duration of their trajectory rather than the whole simulation. You can see the entities present at each time by looking at the `State.poses` dictionary which will contain the current pose of each entity present. The full list of entities can still be accessed by `State.scenario.entities` or `State.all_entities`.
